server:
  port: 5056
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    instance:
      lease-expiration-duration-in-seconds: 2
      lease-renewal-interval-in-seconds: 1
spring:
  application:
    name: gateway-service
  data:
    redis:
      host: localhost
      port: 6379
      password: test1234
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: 'http://localhost:3000'
            allow-credentials: true # JWT 나 쿠키를 사용해 메시지를 보내야 할 경우 true
            allowedHeaders: '*'
            allowedMethods: # 메서드를 명시하지 않으면 안되는 경우도 있기 때문에 메서드는 명시해주는 편이 좋다고 한다.
              - PUT
              - GET
              - POST
              - DELETE
              - OPTIONS
              - PATCH
      routes:
        - id: open-api # id는 아무거나 정해줘도 된다.
          uri: lb://member-service
          predicates:
            - Path=/members/v1/sign-up, /members/v1/sign-in, /oauth/**, /members/v1/passwd, /members/v1/sign-out, /members/v1/checkEmail/{email}, /members/v1/images/{memberId},/members/v1/passwd, /oauth/v1

        - id: member-service
          uri: lb://member-service
          predicates:
            - Path= /members/v1/, /members/v1/passwd,/members/v1/detail,/members/v1/weight,/members/v1/managementData
            - After=2023-11-06T09:39:47.789+09:00[Asia/Seoul]
          filters:
            - name: AuthorizationHeaderFilter
              args: # Config 클래스에 사용할 멤버변수 정의
                headerName: Authorization
        - id: food-service
          uri: lb://food-service
          predicates:
            - Path=/food/**
            # ???? ??(UTC - 1970??? ??? ?? ??? ??)
            # After? ? ???? ? ???? ??? ? ??? ???.
            # ?? ??
            #            - After=2023-11-06T09:40:47.789-07:00[America/Denver]
            # ??? ?? 9?? ???????.
            - After=2023-11-06T09:39:47.789+09:00[Asia/Seoul]
            # header? ?? ??
            # ? ?? ??? ??? ? ??.
        - id: intake-service
          uri: lb://intake-service
          predicates:
            - Path= /target-calorie/v1/{today}, /target-calorie/v1/, /intake/v1/rank, /intake/
            - After=2023-11-06T09:39:47.789+09:00[Asia/Seoul]
          filters:
            - name: AuthorizationHeaderFilter
              args: # Config 클래스에 사용할 멤버변수 정의
                headerName: Authorization

jwt:
  access-token-validity-in-seconds: 86400000
  refresh-token-validity-in-seconds: 864000000
  secret-key: rkGU45258GGhiolLO2465TFY5345kGU45258GGhiolLO2465TFY5345KJHVJGCTHJGBGHCVGFrgtah2ty6ahdsryjms562n357