spring:
  profiles:
    active: local # default
    group:
      local:  # local, common profile을 그룹지어 함께 어플리케이션 구동
        - common
      prod:   # prod, common profile을 그룹지어 함께 어플리케이션 구동
        - common
        -

server:
  port: 5056
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
    instance:
      lease-expiration-duration-in-seconds: 2
      lease-renewal-interval-in-seconds: 1

  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: open-api # id는 아무거나 정해줘도 된다.
          uri: lb://member-service
          predicates:
            - Path=/members/v1/sign-up, /members/v1/sign-in, /oauth/**, /members/v1/passwd # 제외 목록
        - id: member-service
          uri: lb://member-service
          predicates:
            - Path=/members/v1/sign-out, /members/v1/,
            - After=2023-11-06T09:39:47.789+09:00[Asia/Seoul]
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/member-service/(?<segment>.*), /$\{segment}
        - id: food-service
          uri: lb://food-service
          predicates:
            - Path=/food/**
            # ???? ??(UTC - 1970??? ??? ?? ??? ??)
            # After? ? ???? ? ???? ??? ? ??? ???.
            # ?? ??
            #            - After=2023-11-06T09:40:47.789-07:00[America/Denver]
            # ??? ?? 9?? ???????.
            - After=2023-11-06T09:39:47.789+09:00[Asia/Seoul]
            # header? ?? ??
            # ? ?? ??? ??? ? ??.
        - id: intake-service
          uri: lb://intake-service
          predicates:
            - Path=/intake/**


            - Path=/member/**
            # ???? ??(UTC - 1970??? ??? ?? ??? ??)
            # After? ? ???? ? ???? ??? ? ??? ???.
            # ?? ??
            #            - After=2023-11-06T09:40:47.789-07:00[America/Denver]
            # ??? ?? 9?? ???????.
            - After=2023-11-06T09:39:47.789+09:00[Asia/Seoul]
            # header? ?? ??
            # ? ?? ??? ??? ? ??.
        

